NAME = claptrap

all:
	clang++ -Wall -Wextra -Werror claptrap.cpp fragtrap.cpp scavtrap.cpp main.cpp -o $(NAME)

clean:
	rm -rf $(NAME)

re:
	rm -rf $(NAME)
	clang++ -Wall -Wextra -Werror claptrap.cpp fragtrap.cpp scavtrap.cpp main.cpp -o $(NAME)